# Generated by Django 4.1.3 on 2022-12-22 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.SlugField(blank=True, max_length=1024, null=True, unique=True)),
                ('profile_image', models.URLField(blank=True, max_length=2048, null=True)),
                ('description', models.TextField(blank=True, max_length=160, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='app.creatorprofile')),
            ],
            options={
                'verbose_name': 'Creator Profile',
                'verbose_name_plural': 'Creator Profiles',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('slug', models.SlugField(blank=True, max_length=1024, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=148, null=True)),
                ('slug', models.SlugField(blank=True, max_length=1024, null=True, unique=True)),
                ('featured_image', models.URLField(blank=True, max_length=2048, null=True)),
                ('content', models.TextField(max_length=64000, null=True)),
                ('excerpt', models.TextField(max_length=480, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.creatorprofile')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='app.tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
