# Generated by Django 4.1.3 on 2023-02-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_creatorprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='following',
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='app.creatorprofile'),
        ),
    ]
