# Generated by Django 4.1.3 on 2023-02-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_creatorprofile_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='followers',
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='app.creatorprofile'),
        ),
    ]
